services:
  - type: web
    name: verbum-backend
    env: node
    plan: starter
    buildCommand: npm ci --production=false && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: api/v1
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
      # Adicione suas variáveis de ambiente aqui
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: MOODLE_URL
        sync: false
      - key: MOODLE_TOKEN
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: TRIAL_DURATION_DAYS
        value: 7
      - key: TRIAL_EXPIRATION_WARNING_HOURS
        value: 24
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: ./uploads

databases:
  - name: verbum-redis
    plan: starter
    type: redis
