#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting
npm run lint

# Run tests
npm run test

# Check for secrets
if command -v detect-secrets >/dev/null 2>&1; then
  detect-secrets scan --baseline .secrets.baseline
fi
